[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# This config uses Netlify’s official Next.js plugin to handle routing,
# image optimisation and server-side rendering. The build output is
# published from the `.next` directory.